
server:
  port: 8080
spring:
  thymeleaf:
    mode: html
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis2?seUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  downloadDir: E:/java/file_upload_down/download
  uploadDir: E:/java/file_upload_down/upload

person:
  id: 10001
  name: zhangsan
  hobby:
    - sport
    - music
    - read
  map:
    k1: v1
    k2: v2

